version: '2'

services:
    web:
        build:
            context: ./
            dockerfile: docker/web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "8081:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
            - "XDEBUG_CONFIG=remote_host=172.18.0.1 remote_port=9000"
    database:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=lumenjwt"
        ports:
            - "33061:3306"
